# Generated by Django 3.0.5 on 2020-05-30 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='기사 제목')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('text', models.CharField(max_length=1000, verbose_name='기사 내용')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
    ]
