# Generated by Django 3.0.5 on 2020-05-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.CharField(default='', max_length=200),
        ),
    ]
