# Generated by Django 3.0.5 on 2020-05-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0002_auto_20200531_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='scrap',
            field=models.IntegerField(default=0, verbose_name='스크랩 수'),
        ),
    ]
