# Generated by Django 3.0.5 on 2020-06-02 11:18

from django.db import migrations, models
import sg.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0003_writing_scrap'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='writing',
            managers=[
                ('objects', sg.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='writing',
            name='writer',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
    ]
