# Generated by Django 3.0.5 on 2020-06-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0005_writing_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writing',
            options={'ordering': ['pub_date']},
        ),
    ]
