# Generated by Django 3.0.5 on 2020-06-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0006_auto_20200610_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='photo',
            field=models.CharField(default='', max_length=500, verbose_name='사진 url'),
        ),
    ]
