# Generated by Django 3.0.5 on 2020-06-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0007_writing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='writer',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
