# Generated by Django 3.0.5 on 2020-06-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0008_auto_20200610_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writing',
            options={'ordering': ['-pub_date']},
        ),
    ]
