# Generated by Django 3.0.5 on 2020-06-14 23:25

from django.db import migrations, models
import django.utils.timezone
import sg.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0009_auto_20200610_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.CharField(default=None, max_length=20, verbose_name='사용자 id')),
                ('title', models.CharField(max_length=100, verbose_name='기사 제목')),
                ('article_id', models.IntegerField(default=0, verbose_name='기사 번호')),
                ('category', models.CharField(default='', max_length=50, verbose_name='카테고리')),
                ('writer', models.CharField(default=None, max_length=20, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='스크랩 날짜')),
                ('scrap', models.IntegerField(default=0, verbose_name='스크랩 수')),
            ],
            managers=[
                ('objects', sg.managers.UserManager()),
            ],
        ),
    ]
