# Generated by Django 3.0.5 on 2020-06-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sg', '0010_scraplist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraplist',
            old_name='pub_date',
            new_name='scrap_date',
        ),
    ]
